services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"