name: Deploy to k8s

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Deploying
        run: bash cd/deploy.sh ${{ secrets.KUBECONFIG }}
  
