name: Deploy to k8s

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      - run: kubectl apply -f ./k8s/
  
