name: Deploy to k8s

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Create .kube directory
        run: mkdir -p $HOME/.kube
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./k8s/
  
