name: Deploy to k8s

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/checkout@v4
        with:
          name: code
          path: .
      - name: Deploying manifests
        run: bash cd/deploy.sh ${{ secrets.KUBECONFIG }}
