name: docker-build-push

on:
  workflow_call:

env:
  docker_username: gibbus2
  docker_password: ${{ secrets.GITHUB_TOKEN }}  
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Download repository
      uses: actions/checkout@v4
    - name: build docker
      run: bash ci/build-docker.sh
    - name: push docker
      run: bash ci/push-docker.sh
    
