name: main

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  docker_username: gibbus2
  docker_password: ${{ secrets.GITHUB_TOKEN }}  
jobs:
  call-build:
    uses: ./.github/workflows/build.yaml

  call-docker-build-push:
    needs: [call-build, call-test]
    permissions:
        packages: write
    uses: ./.github/workflows/docker-build-push.yaml

  call-deploy-helm:
    needs: [call-build, call-test]
    secrets: inherit
    uses: ./.github/workflows/deploy-helm.yml
    
  call-test:
    uses: ./.github/workflows/test.yaml
    
  call-linter:
    uses: ./.github/workflows/linter.yaml

  call-deploy:
    needs: [call-deploy-helm, call-docker-build-push]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    
  call-functinal-test:
    needs: [call-deploy]
    secrets: inherit
    uses: ./.github/workflows/functinal-test.yaml
    
