name: main

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

env:
  docker_username: gibbus2
  docker_password: ${{ secrets.GITHUB_TOKEN }}  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download repository
      uses: actions/checkout@v4
    - name: Building Frontend & Backend
      run: bash ci/build.sh
    - name: Upload Repository
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: .

  docker-image-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Download repository
      uses: actions/checkout@v4
    - name: build docker
      run: bash ci/build-docker.sh
    - name: push docker
      run: bash ci/push-docker.sh
    

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Repository
      uses: actions/checkout@v4
    - name: Running Unit Tests
      run: bash ci/test.sh
    
