name: main

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download repository
      uses: actions/checkout@v4
    - name: Building Frontend & Backend
      run: bash ci/build.sh
    - name: Upload Repository
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: .

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running Unit Tests
      run: bash ci/test.sh
    
